from __future__ import annotations

import pandas as pd

from harmonize_variables import CANONICAL_SPECS, EXCLUDED_CANONICAL, build_crosswalk_df, harmonize_wave
from parse_lapop_brazil import read_wave_metadata
from utils import CORE_WAVES, INTERIM_DIR


def build_wave_availability() -> pd.DataFrame:
    rows = []
    for year in CORE_WAVES:
        meta = read_wave_metadata(year)
        cols = set(meta.column_names)
        for canon, spec in CANONICAL_SPECS.items():
            if spec.get("type") == "constant":
                rows.append(
                    {
                        "survey_year": year,
                        "raw_variable": None,
                        "present": True,
                        "canonical_variable": canon,
                        "notes": "Constant field generated by the harmonizer.",
                    }
                )
                continue
            raw_var = spec["raw"].get(year)
            rows.append(
                {
                    "survey_year": year,
                    "raw_variable": raw_var,
                    "present": bool(raw_var in cols) if raw_var else False,
                    "canonical_variable": canon,
                    "notes": spec["transform"],
                }
            )
        for canon, note in EXCLUDED_CANONICAL.items():
            rows.append(
                {
                    "survey_year": year,
                    "raw_variable": None,
                    "present": False,
                    "canonical_variable": canon,
                    "notes": note,
                }
            )
    return pd.DataFrame(rows)


def build_core_panel() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    waves = [harmonize_wave(year) for year in CORE_WAVES]
    core = pd.concat(waves, ignore_index=True)

    desired_columns = [
        "survey_year",
        "wave_label",
        "country",
        "weight",
        "upm",
        "cluster",
        "state_name_raw",
        "state_name",
        "municipality_name_raw",
        "municipality_name",
        "bairro_raw",
        "interview_date",
        "respondent_gender_raw",
        "respondent_gender",
        "female",
        "age_raw",
        "age",
        "birth_year_raw",
        "married_raw",
        "married",
        "urban_raw",
        "urban",
        "education_raw",
        "education_category",
        "education_years_raw",
        "white_raw",
        "white",
        "working_raw",
        "working",
        "trust_inst_respect",
        "trust_rights_protected",
        "trust_proud_system",
        "trust_support_system",
        "trust_parties",
        "trust_president",
        "trust_municipal_gov",
        "trust_elections",
        "democracy_best_form",
        "democracy_satisfaction",
        "democracy_voice_matters",
        "democracy_understands_politics",
        "ideology_raw",
        "ideology_scale",
        "interest_politics_raw",
        "interest_politics",
    ]
    core = core[desired_columns]

    crosswalk = build_crosswalk_df()
    availability = build_wave_availability()
    INTERIM_DIR.mkdir(parents=True, exist_ok=True)
    crosswalk.to_csv(INTERIM_DIR / "variable_crosswalk.csv", index=False)
    availability.to_csv(INTERIM_DIR / "wave_variable_availability.csv", index=False)
    return core, crosswalk, availability


if __name__ == "__main__":
    build_core_panel()
